In [2]:
from google.colab import drive
drive.mount('/content/drive')
!pwd

Mounted at /content/drive
/content


In [3]:
!ls
%cd drive/MyDrive/DA/clustering
!pwd

drive  sample_data
/content/drive/MyDrive/DA/clustering
/content/drive/MyDrive/DA/clustering


In [4]:
import numpy as np
import pandas as pd

####Load dataset

In [119]:
df_data_org = pd.read_csv('football_data.csv', na_values=np.NaN)
print(df_data_org.shape)
display(df_data_org.head())
display(df_data_org.info())
display(df_data_org.describe())

(18207, 89)


Unnamed: 0      ID  ... GKReflexes  Release Clause
0           0  158023  ...        8.0         €226.5M
1           1   20801  ...       11.0         €127.1M
2           2  190871  ...       11.0         €228.1M
3           3  193080  ...       94.0         €138.6M
4           4  192985  ...       13.0         €196.4M

[5 rows x 89 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 89 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                18207 non-null  int64  
 1   ID                        18207 non-null  int64  
 2   Name                      18207 non-null  object 
 3   Age                       18207 non-null  int64  
 4   Photo                     18207 non-null  object 
 5   Nationality               18207 non-null  object 
 6   Flag                      18207 non-null  object 
 7   Overall                   18207 non-null  int64  
 8   Potential                 18207 non-null  int64  
 9   Club                      17966 non-null  object 
 10  Club Logo                 18207 non-null  object 
 11  Value                     18207 non-null  object 
 12  Wage                      18207 non-null  object 
 13  Special                   18207 non-null  int64  
 14  Prefer

None

Unnamed: 0             ID  ...  GKPositioning    GKReflexes
count  18207.000000   18207.000000  ...   18159.000000  18159.000000
mean    9103.000000  214298.338606  ...      16.388898     16.710887
std     5256.052511   29965.244204  ...      17.034669     17.955119
min        0.000000      16.000000  ...       1.000000      1.000000
25%     4551.500000  200315.500000  ...       8.000000      8.000000
50%     9103.000000  221759.000000  ...      11.000000     11.000000
75%    13654.500000  236529.500000  ...      14.000000     14.000000
max    18206.000000  246620.000000  ...      90.000000     94.000000

[8 rows x 44 columns]

####Drop rows having no position info... as these cols also do not have values for many other attributes


In [120]:
df_data = df_data_org[df_data_org['Position'].notna()]
print(df_data.shape)

(18147, 89)


####Drop nonrequired cols

In [121]:
df_data = df_data.drop(['Unnamed: 0','ID','Name','Photo','Nationality','Flag','Club','Club Logo','Joined','Loaned From','Contract Valid Until'], axis=1)
print(df_data.shape)

(18147, 78)


####Convert currency columns to float

In [122]:
df_data['Value'] = df_data['Value'].apply(lambda c: float(c[1:-1]) if (pd.notnull(c) and (c[-1]=='M' or c[-1]=='K')) else 0.0)
print(df_data['Value'].shape)

df_data['Wage'] = df_data['Wage'].apply(lambda c: float(c[1:-1]) if (pd.notnull(c) and (c[-1]=='M' or c[-1]=='K')) else 0.0)
print(df_data['Wage'].shape)

(18147,)
(18147,)


####Convert real face to binary values

In [123]:
print(df_data['Real Face'].unique())
df_data['Real Face'] = df_data['Real Face'].apply(lambda c: 1 if c=='Yes' else 0)
print(df_data['Real Face'].shape)
print(df_data['Real Face'].unique())

['Yes' 'No']
(18147,)
[1 0]


####Convert body type to numeric ordinal values

In [124]:
print(len(df_data[df_data['Body Type']=='Normal']))
print(len(df_data[df_data['Body Type']=='Stocky']))
print(len(df_data[df_data['Body Type']=='Lean']))

df_data['Body Type'] = df_data['Body Type'].apply(lambda c: 'Normal' if c not in ['Normal','Stocky','Lean'] else c)
print(df_data['Body Type'].unique())

cat_to_num = {"Body Type":{'Lean':0, 'Normal':1, 'Stocky':2}}
df_data = df_data.replace(cat_to_num)
print(df_data['Body Type'].unique())

10588
1140
6412
['Normal' 'Lean' 'Stocky']
[1 0 2]


####Convert work rate to ordinal values

In [125]:
print(df_data['Work Rate'].unique())
df_data['Attack Work Rate'] = df_data['Work Rate'].apply(lambda c: c.split('/ ')[0])
df_data['Defense Work Rate'] = df_data['Work Rate'].apply(lambda c: c.split('/ ')[1])
print(df_data['Attack Work Rate'].unique())
print(df_data['Defense Work Rate'].unique())
cat_to_num = {"Attack Work Rate":{'Low':0, 'Medium':1, 'High':2}, "Defense Work Rate":{'Low':0, 'Medium':1, 'High':2}}
df_data = df_data.replace(cat_to_num)
print(df_data['Attack Work Rate'].unique())
print(df_data['Defense Work Rate'].unique())
df_data = df_data.drop(['Work Rate'], axis=1)

['Medium/ Medium' 'High/ Low' 'High/ Medium' 'High/ High' 'Medium/ High'
 'Medium/ Low' 'Low/ High' 'Low/ Medium' 'Low/ Low']
['Medium' 'High' 'Low']
['Medium' 'Low' 'High']
[1 2 0]
[1 0 2]


####Convert preferred foot to binary

In [126]:
print(df_data['Preferred Foot'].unique())
df_data['Preferred Foot'] = df_data['Preferred Foot'].apply(lambda c: 1 if c=='Right' else 0)
print(df_data['Preferred Foot'].shape)
print(df_data['Preferred Foot'].unique())

['Left' 'Right']
(18147,)
[0 1]


####Convert height to float

In [127]:
print(df_data['Height'].unique())
df_data['Height'] = df_data['Height'].apply(lambda c: float(c[0]+'.'+c[2]))
print(df_data['Height'].unique())

["5'7" "6'2" "5'9" "6'4" "5'11" "5'8" "6'0" "5'6" "5'10" "6'6" "6'1" "5'4"
 "6'3" "5'5" "6'5" "6'7" "5'3" "5'2" "6'8" "5'1" "6'9"]
[5.7 6.2 5.9 6.4 5.1 5.8 6.  5.6 6.6 6.1 5.4 6.3 5.5 6.5 6.7 5.3 5.2 6.8
 6.9]


####Convert weight to float

In [128]:
print(df_data['Weight'].unique())
df_data['Weight'] = df_data['Weight'].apply(lambda c: int(c[:-3]))
print(df_data['Weight'].unique())

['159lbs' '183lbs' '150lbs' '168lbs' '154lbs' '163lbs' '146lbs' '190lbs'
 '181lbs' '192lbs' '176lbs' '172lbs' '148lbs' '165lbs' '196lbs' '161lbs'
 '187lbs' '212lbs' '170lbs' '203lbs' '157lbs' '185lbs' '130lbs' '174lbs'
 '207lbs' '134lbs' '141lbs' '152lbs' '179lbs' '132lbs' '201lbs' '198lbs'
 '209lbs' '214lbs' '143lbs' '205lbs' '137lbs' '194lbs' '216lbs' '139lbs'
 '220lbs' '126lbs' '218lbs' '123lbs' '227lbs' '128lbs' '223lbs' '225lbs'
 '121lbs' '115lbs' '117lbs' '236lbs' '229lbs' '243lbs' '110lbs' '119lbs'
 '234lbs']
[159 183 150 168 154 163 146 190 181 192 176 172 148 165 196 161 187 212
 170 203 157 185 130 174 207 134 141 152 179 132 201 198 209 214 143 205
 137 194 216 139 220 126 218 123 227 128 223 225 121 115 117 236 229 243
 110 119 234]


####Convert release clause to float

In [129]:
df_data['Release Clause'] = df_data['Release Clause'].apply(lambda c: float(c[1:-1]) if (pd.notnull(c) and (c[-1]=='M' or c[-1]=='K')) else 0.0)
df_data['Release Clause'].fillna(df_data['Release Clause'].median(), inplace = True)
print(df_data['Release Clause'].shape)
print(df_data['Release Clause'].unique())


(18147,)
[226.5 127.1 228.1 ...  67.  101.  147. ]


####Convert positional scores to float

In [130]:
scores = ['LS','ST','RS','LW','LF','CF','RF','RW','LAM','CAM','RAM','LM','LCM','CM','RCM','RM','LWB','LDM','CDM','RDM','RWB','LB','LCB','CB','RCB','RB']
for score in scores:
    df_data[score] = df_data[score].apply(lambda c: float(c.split('+')[0]) if pd.notnull(c) else 0.0)
    df_data[score].fillna(df_data[score].median(), inplace = True)
    print(score,df_data[score].shape,df_data[score][:3],'\n')  

df_data = df_data.drop(['Position'], axis=1)

LS (18147,) 0    88.0
1    91.0
2    84.0
Name: LS, dtype: float64 

ST (18147,) 0    88.0
1    91.0
2    84.0
Name: ST, dtype: float64 

RS (18147,) 0    88.0
1    91.0
2    84.0
Name: RS, dtype: float64 

LW (18147,) 0    92.0
1    89.0
2    89.0
Name: LW, dtype: float64 

LF (18147,) 0    93.0
1    90.0
2    89.0
Name: LF, dtype: float64 

CF (18147,) 0    93.0
1    90.0
2    89.0
Name: CF, dtype: float64 

RF (18147,) 0    93.0
1    90.0
2    89.0
Name: RF, dtype: float64 

RW (18147,) 0    92.0
1    89.0
2    89.0
Name: RW, dtype: float64 

LAM (18147,) 0    93.0
1    88.0
2    89.0
Name: LAM, dtype: float64 

CAM (18147,) 0    93.0
1    88.0
2    89.0
Name: CAM, dtype: float64 

RAM (18147,) 0    93.0
1    88.0
2    89.0
Name: RAM, dtype: float64 

LM (18147,) 0    91.0
1    88.0
2    88.0
Name: LM, dtype: float64 

LCM (18147,) 0    84.0
1    81.0
2    81.0
Name: LCM, dtype: float64 

CM (18147,) 0    84.0
1    81.0
2    81.0
Name: CM, dtype: float64 

RCM (18147,) 0    84.0
1  

####Set nan values to median of resp col

In [134]:
for col in df_data.columns:
    df_data[col].fillna(df_data[col].median(), inplace=True)

display(df_data.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 18147 entries, 0 to 18206
Data columns (total 78 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Age                       18147 non-null  int64  
 1   Overall                   18147 non-null  int64  
 2   Potential                 18147 non-null  int64  
 3   Value                     18147 non-null  float64
 4   Wage                      18147 non-null  float64
 5   Special                   18147 non-null  int64  
 6   Preferred Foot            18147 non-null  int64  
 7   International Reputation  18147 non-null  float64
 8   Weak Foot                 18147 non-null  float64
 9   Skill Moves               18147 non-null  float64
 10  Body Type                 18147 non-null  int64  
 11  Real Face                 18147 non-null  int64  
 12  Jersey Number             18147 non-null  float64
 13  Height                    18147 non-null  float64
 14  Weight

None

####Save the processed dataframe to csv

In [135]:
df_data.to_csv('processed_football_data.csv', index=False)